name: Publish release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  publish:
    uses: wphillipmoore/standard-actions/.github/workflows/publish-release.yml@v1.3
    permissions:
      contents: write
      pull-requests: write
    with:
      ecosystem: go
      version-command: >-
        grep -oP 'Version\s*=\s*"\K[^"]+' mqrestadmin/version.go
      build-command: >-
        go build ./... && go vet ./... && go test -race -count=1 ./...
      sbom-output-file: "dist/mqrestadmin-$VERSION.cdx.json"
      release-title: mqrestadmin
      release-notes: |
        ## Installation

        ```bash
        go get github.com/wphillipmoore/mq-rest-admin-go@v$VERSION
        ```

        ## Links

        - [Go Package](https://pkg.go.dev/github.com/wphillipmoore/mq-rest-admin-go@v$VERSION)
        - [Documentation](https://wphillipmoore.github.io/mq-rest-admin-go/)
      release-artifacts: "dist/*"
      version-file: mqrestadmin/version.go
      version-regex: '(Version\s*=\s*\").*(\"\s*)'
      version-replacement: '\g<1>{version}\2'
      develop-version-command: >-
        grep -oP 'Version\s*=\s*"\K[^"]+'
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
